version: '3'
services:
  event-service:
    build: .
    image: ghcr.io/langrenn-sprint/event-service:test
    ports:
      - 8080:8080
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - USERS_HOST_SERVER=user-service
      - USERS_HOST_PORT=8080
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
    depends_on:
      - user-service
      - mongodb
  user-service:
    image: ghcr.io/langrenn-sprint/user-service:latest
    ports:
      - 8081:8080
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXP_DELTA_SECONDS=${JWT_EXP_DELTA_SECONDS}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
